name: Danger Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - run: npm install prettier
    - name: Danger JS Action
      uses: danger/danger-js@9.1.8
      env:
        DANGER_DISABLE_TRANSPILATION: "true"
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

